# Generated by Django 3.2.25 on 2024-05-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDept',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('parentId', models.CharField(default='', help_text='父id', max_length=64, verbose_name='父id')),
                ('deptName', models.CharField(default='', help_text='部门名称', max_length=64, verbose_name='部门名称')),
                ('deptId', models.CharField(default='', help_text='部门id', max_length=64, unique=True, verbose_name='部门id')),
                ('orderNum', models.IntegerField(default=0, help_text='排序', verbose_name='排序')),
                ('leader', models.CharField(default='', help_text='负责人', max_length=64, verbose_name='负责人')),
                ('phone', models.CharField(default='', help_text='联系电话', max_length=64, verbose_name='联系电话')),
                ('email', models.CharField(default='', help_text='邮箱', max_length=64, verbose_name='邮箱')),
                ('status', models.CharField(default='', help_text='启用状态 （0正常 1停用）', max_length=64, verbose_name='启用状态')),
                ('delFlag', models.CharField(default='', help_text='是否删除 （0存在 2删除）', max_length=64, verbose_name='是否删除')),
                ('ancestors', models.CharField(default='', help_text='上级目录id', max_length=64, verbose_name='上级目录id')),
                ('createBy', models.CharField(default='', help_text='创建者', max_length=64, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '部门管理',
                'db_table': 'system_dept',
            },
        ),
    ]
