# Generated by Django 3.2.25 on 2024-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInit',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, help_text='备注信息', max_length=64, verbose_name='备注信息')),
                ('createBy', models.CharField(blank=True, help_text='创建者', max_length=64, verbose_name='创建者')),
                ('Init', models.BooleanField(blank=True, default=False, help_text='是否已经初始化数据库')),
            ],
            options={
                'verbose_name': '核心模型',
                'verbose_name_plural': '核心模型',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemMenu',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, help_text='备注信息', max_length=64, verbose_name='备注信息')),
                ('createBy', models.CharField(blank=True, help_text='创建者', max_length=64, verbose_name='创建者')),
                ('menuId', models.CharField(default='', help_text='菜单ID', max_length=64, unique=True, verbose_name='菜单ID')),
                ('menuName', models.CharField(default='', help_text='菜单名称', max_length=64, verbose_name='菜单名称')),
                ('parentId', models.CharField(default='', help_text='父菜单ID', max_length=64, verbose_name='父菜单ID')),
                ('orderNum', models.IntegerField(default=0, help_text='显示顺序', verbose_name='显示顺序')),
                ('path', models.CharField(default='', help_text='路由地址', max_length=64, verbose_name='路由地址')),
                ('component', models.CharField(default='', help_text='组件路径', max_length=64, verbose_name='组件路径')),
                ('query', models.CharField(default='', help_text='路由参数', max_length=64, verbose_name='路由参数')),
                ('isFrame', models.CharField(default='', help_text='是否为外链（0是 1否）', max_length=4, verbose_name='是否为外链（0是 1否）')),
                ('isCache', models.CharField(default='', help_text='是否缓存（0缓存 1不缓存）', max_length=4, verbose_name='是否缓存（0缓存 1不缓存）')),
                ('visible', models.CharField(default='', help_text='菜单状态（0显示 1隐藏）', max_length=4, verbose_name='菜单状态（0显示 1隐藏）')),
                ('menuType', models.CharField(default='', help_text='菜单类型（M目录 C菜单 F按钮）', max_length=4, verbose_name='菜单类型（M目录 C菜单 F按钮）')),
                ('status', models.CharField(default='', help_text='菜单状态（0正常 1停用）', max_length=4, verbose_name='菜单状态（0正常 1停用）')),
                ('perms', models.CharField(default='', help_text='权限标识', max_length=32, verbose_name='权限标识')),
                ('icon', models.CharField(default='', help_text='菜单图', max_length=32, verbose_name='菜单图')),
            ],
            options={
                'verbose_name': '目录管理',
                'db_table': 'system_menu',
            },
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, help_text='备注信息', max_length=64, verbose_name='备注信息')),
                ('createBy', models.CharField(blank=True, help_text='创建者', max_length=64, verbose_name='创建者')),
                ('roleId', models.CharField(default='', help_text='角色id', max_length=64, unique=True, verbose_name='角色id')),
                ('roleName', models.CharField(default='', help_text='角色名称', max_length=64, verbose_name='角色名称')),
                ('roleKey', models.CharField(default='', help_text='角色权限字符', max_length=64, verbose_name='角色权限字符')),
                ('roleSort', models.IntegerField(default=0, help_text='角色排序', verbose_name='角色排序')),
                ('roleAdmin', models.BooleanField(default=False, help_text='是否是超级管理员', max_length=64, verbose_name='是否是超级管理员')),
                ('status', models.CharField(default='0', help_text='启用状态 （0正常 1停用）', max_length=4, verbose_name='启用状态 （0正常 1停用）')),
                ('menuCheckStrictly', models.BooleanField(default=True, help_text='菜单树选择项是否关联显示', verbose_name='菜单树选择项是否关联显示')),
                ('deptCheckStrictly', models.BooleanField(default=True, help_text='部门树选择项是否关联显示', verbose_name='部门树选择项是否关联显示')),
                ('delFlag', models.CharField(default='0', help_text='是否删除 （0代表存在 2代表删除）', max_length=4, verbose_name='是否删除 （0代表存在 2代表删除）')),
            ],
            options={
                'verbose_name': '角色管理',
                'db_table': 'system_role',
            },
        ),
        migrations.CreateModel(
            name='SystemRoleMenu',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, help_text='备注信息', max_length=64, verbose_name='备注信息')),
                ('createBy', models.CharField(blank=True, help_text='创建者', max_length=64, verbose_name='创建者')),
                ('menuId', models.CharField(default='', help_text='菜单id', max_length=64, verbose_name='菜单id')),
                ('roleId', models.CharField(default='', help_text='角色id', max_length=64, verbose_name='角色id')),
            ],
            options={
                'verbose_name': '角色与目录关系映射',
                'db_table': 'system_role_menu',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, help_text='备注信息', max_length=64, verbose_name='备注信息')),
                ('createBy', models.CharField(blank=True, help_text='创建者', max_length=64, verbose_name='创建者')),
                ('userId', models.CharField(default='', help_text='用户id', max_length=64, unique=True, verbose_name='用户id')),
                ('deptId', models.CharField(default='', help_text='部门id', max_length=64, verbose_name='部门id')),
                ('username', models.CharField(default='', help_text='用户账号', max_length=64, verbose_name='用户账号')),
                ('nickName', models.CharField(default='', help_text='用户昵称', max_length=64, verbose_name='用户昵称')),
                ('userType', models.CharField(default=False, help_text='用户类型（00系统用户）', max_length=4, verbose_name='用户类型（00系统用户）')),
                ('email', models.CharField(default='', help_text='邮箱', max_length=64, verbose_name='邮箱')),
                ('phone', models.CharField(default='', help_text='手机号码', max_length=64, verbose_name='手机号码')),
                ('avatar', models.CharField(default='', help_text='头像', max_length=64, verbose_name='头像')),
                ('password', models.CharField(default='', help_text='密码（加密后）', max_length=64, verbose_name='密码（加密后）')),
                ('status', models.CharField(default='0', help_text='帐号状态（0正常 1停用）', max_length=4, verbose_name='帐号状态（0正常 1停用）')),
                ('delFlag', models.CharField(default='0', help_text='删除标志（0代表存在 2代表删除）', max_length=4, verbose_name='删除标志（0代表存在 2代表删除）')),
                ('loginIp', models.CharField(default='', help_text='最后登陆ip', max_length=64, verbose_name='最后登陆ip')),
                ('loginDate', models.CharField(default='', help_text='最后登陆日期', max_length=64, verbose_name='最后登陆日期')),
            ],
            options={
                'verbose_name': '用户管理',
                'db_table': 'system_user',
            },
        ),
        migrations.CreateModel(
            name='SystemUserRole',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('remark', models.CharField(blank=True, help_text='备注信息', max_length=64, verbose_name='备注信息')),
                ('createBy', models.CharField(blank=True, help_text='创建者', max_length=64, verbose_name='创建者')),
                ('userId', models.CharField(default='', help_text='用户id', max_length=64, verbose_name='菜单id')),
                ('roleId', models.CharField(default='', help_text='角色id', max_length=64, verbose_name='角色id')),
            ],
            options={
                'verbose_name': '角色与人员关系映射',
                'db_table': 'system_role_user',
            },
        ),
        migrations.AddField(
            model_name='systemdept',
            name='remark',
            field=models.CharField(blank=True, help_text='备注信息', max_length=64, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='systemdept',
            name='createBy',
            field=models.CharField(blank=True, help_text='创建者', max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='systemdept',
            name='delFlag',
            field=models.CharField(default='0', help_text='是否删除 （0存在 2删除）', max_length=4, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='systemdept',
            name='email',
            field=models.CharField(default='', help_text='邮箱', max_length=32, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='systemdept',
            name='leader',
            field=models.CharField(default='', help_text='负责人', max_length=32, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='systemdept',
            name='phone',
            field=models.CharField(default='', help_text='联系电话', max_length=32, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='systemdept',
            name='status',
            field=models.CharField(default='0', help_text='启用状态 （0正常 1停用）', max_length=4, verbose_name='启用状态'),
        ),
    ]
