# Generated by Django 3.2.25 on 2024-05-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20240531_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systeminit',
            options={'verbose_name': '部门管理'},
        ),
        migrations.AlterModelTable(
            name='systeminit',
            table='system_init',
        ),
    ]
